import React, { useState } from "react";
import {View,Text, TouchableOpacity, FlatList} from "react-native";
import { globalStyles } from '../styles/global'

export default function Forum({ navigation }){

    const [posts, setPosts] = useState([
        {title: 'example post 1',
        descrption: 'this is where you would ramble on about whatever you are posting on the forum',
        author: 'this will be retrieved from the session or state',
        time_posted: 'autogenerated'},
        {title: 'ex post 2',
        descrption: 'descrip 2',
        author: 'author 2',
        time_posted: 'autogenerated'},
        {title: 'ex post 2',
        descrption: 'descrip 2',
        author: 'author 2',
        time_posted: 'autogenerated'},
    ]);


    return(
        <View style={globalStyles.container}>
            {/* <FlatList
                data={posts}
                renderItem={({i}) => (
                <TouchableOpacity onPress={() => navigation.navigate('Post', i)}>
                    <Text style={globalStyles.titleText}>{i.title}</Text>
                </TouchableOpacity>)
                }
            /> */}
            <FlatList
                data={posts}
                renderItem={
                    // this only works here if you use 'item' in renderItem
                    ({item}) => (
                        <TouchableOpacity onPress={() => navigation.navigate('Post', item)}>
                            <Text>{ item.title }</Text> 
                        </TouchableOpacity>
                    )
                }
            />

            <Text>hi</Text>
        </View>
    )
}

